# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f698eeadd6b66c3f08915b166d49e9362418021edb00e8491c540de0b96d89740d1f7b4f294b209ddbbbac6caacab69a7a803614825789f151b96f120a04b96c

test:
  secret_key_base: 7c9f1d230e11ff2ca00a79c0e405208d32ee96f57cd2c2fb2f911af066c8f989bf7a94f75eaec961fd14733e4c1fad7acfd4e019a67eb1852e54cfa42d5070d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
